// Pending-embedding backlog.
//
// There is no queue table: the invariant "this memory has no chunk vectors built
// by the active model from the text it currently holds" IS the backlog, computed
// straight from the embeddings table. When the provider is down, sync/save_memory
// write the memory to DB + FTS (keyword search keeps working) and simply skip the
// vectors; sync and the MCP server call drainPending() whenever the provider is
// reachable, so the backlog self-heals with no extra state to maintain.

import { embed, activeModel } from './embed.js';
import { chunkMemory, embedHash } from './chunk.js';

// One predicate covers every way a memory's vectors can be wrong: never
// generated, generated by a different model, or generated from content that has
// since changed.
//
// The embed_hash clause is what closed the 2026-08-28 gap. The old predicate was
// "vector missing OR wrong model", so a memory whose re-embed failed after an
// edit kept its previous vector — right model, stale content — and read as fully
// indexed forever. 14 memories across 7 projects had silently drifted that way,
// one of them carrying a vector 10 weeks older than the text it claimed to
// represent. Anything that changes the embedded text now changes the hash.
const PENDING_WHERE = `
  NOT EXISTS (
    SELECT 1 FROM embeddings e
    WHERE e.memory_id = m.id AND e.model = ? AND e.embed_hash = m.embed_hash
  )
`;

export function countPending(db) {
  return db.prepare(`SELECT COUNT(*) AS n FROM memories m WHERE ${PENDING_WHERE}`).get(activeModel()).n;
}

// Embed one memory as N chunks and swap the whole set in atomically.
// Returns { ok: true, model, chunks } or the failing chunk's
// { ok: false, reason, message } passed straight through from embed(), so the
// caller can tell the user which failure it actually was rather than guessing
// "provider down". reembed.js also needs the model named, to guard against
// writing a mixed-model table.
//
// All-or-nothing on purpose: a partial write would leave a long memory holding
// vectors for its first few sections and none for the rest, which satisfies the
// pending predicate and so would never be retried — a quieter version of the bug
// this file exists to prevent. On failure the previous vectors stay in place, so
// the memory remains searchable on older text until the next drain succeeds.
export async function embedMemory(db, mem) {
  const chunks = chunkMemory(mem.title, mem.content);
  const hash = mem.embed_hash || embedHash(mem.title, mem.content);

  const embedded = [];
  for (const chunk of chunks) {
    const result = await embed(chunk.text); // embed() applies EMBED_MAX_CHARS
    if (!result.ok) return result;
    embedded.push({ ...chunk, vector: result.vector, model: result.model });
  }

  const now = new Date().toISOString();
  const insert = db.prepare(`
    INSERT INTO embeddings (memory_id, chunk_index, start_char, end_char, vector, model, embed_hash, generated_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);
  db.exec('BEGIN');
  try {
    // Chunk counts shrink as well as grow, so clear rather than upsert —
    // otherwise an edited-down memory keeps vectors for text it no longer has.
    db.prepare('DELETE FROM embeddings WHERE memory_id = ?').run(mem.id);
    for (const c of embedded) {
      insert.run(mem.id, c.index, c.start, c.end, JSON.stringify(c.vector), c.model, hash, now);
    }
    db.exec('COMMIT');
  } catch (err) {
    db.exec('ROLLBACK');
    throw err;
  }
  return { ok: true, model: embedded[0].model, chunks: embedded.length };
}

// Re-embed every pending memory. Probes the provider on one throwaway call first
// so a down provider costs one failed request, not one per row; aborts after 3
// consecutive mid-run failures for the same reason.
//
// Returns { drained, remaining }, plus { reason, message } whenever something was
// left behind — a caller reporting "N still pending" without saying why is what
// let a healthy-provider failure hide in plain sight.
export async function drainPending(db, log = () => {}) {
  const rows = db.prepare(`
    SELECT m.id, m.title, m.content, m.embed_hash FROM memories m
    WHERE ${PENDING_WHERE}
    ORDER BY m.id
  `).all(activeModel());
  if (!rows.length) return { drained: 0, remaining: 0 };

  const probe = await embed('embedding provider probe');
  if (!probe.ok) {
    return { drained: 0, remaining: rows.length, reason: probe.reason, message: probe.message };
  }

  let drained = 0, consecutiveFailures = 0, lastFailure = null;

  for (const r of rows) {
    const result = await embedMemory(db, r);
    if (!result.ok) {
      lastFailure = result;
      if (++consecutiveFailures >= 3) break; // provider dropped mid-drain
      continue;
    }
    consecutiveFailures = 0;
    drained++;
    if (drained % 25 === 0) log(`  backlog: ${drained}/${rows.length}`);
  }

  const remaining = rows.length - drained;
  return remaining && lastFailure
    ? { drained, remaining, reason: lastFailure.reason, message: lastFailure.message }
    : { drained, remaining };
}

// How often the resident backfill loop re-checks. Cheap enough to be frequent:
// an empty backlog costs one indexed COUNT and never touches the provider, and a
// down provider costs one failed probe, because drainPending() probes before it
// reads a single row.
export const BACKFILL_INTERVAL_MS = Number(process.env.BACKFILL_INTERVAL_MS) || 60_000;

const unrefSleep = ms => new Promise(resolve => {
  const timer = setTimeout(resolve, ms);
  timer.unref?.(); // never hold the process open on our account
});

// Keep retrying the backlog for the life of the process. Returns a stop function.
//
// Defect 2 of the 2026-08-28 report was that a `/mcp` reconnect "didn't drain the
// backlog". The drain was never broken — it simply only ever got one attempt, at
// the instant of boot. The provider is routinely not ready right then (Ollama
// still starting, or the model cold), and reconnecting the server is itself just
// another boot, so the user's natural remedy lands in exactly the same window and
// appears to do nothing. Reproduced 2026-08-28: booting against a down provider
// left 3 memories pending, and bringing the provider back up changed nothing
// until the next sync.
//
// The old call site was also `.catch(() => {})`, so a genuine exception here was
// indistinguishable from "nothing to do" — the same swallowing that made the
// original outage unreadable. Failures are reported now, never discarded.
export function startBackfillLoop(db, log = () => {}, opts = {}) {
  const {
    intervalMs = BACKFILL_INTERVAL_MS,
    count = countPending,
    drain = drainPending,
    sleep = unrefSleep,
  } = opts;

  let stopped = false;
  let lastReason = null; // so a persistently down provider is reported once, not every minute

  (async () => {
    while (!stopped) {
      try {
        if (count(db)) {
          const { drained, remaining, reason, message } = await drain(db);
          if (drained) log(`backfilled ${drained} pending embedding(s)`);
          if (remaining) {
            if (reason !== lastReason) log(`${remaining} memorie(s) still pending — ${reason}: ${message}`);
            lastReason = reason;
          } else {
            lastReason = null;
          }
        }
      } catch (err) {
        log(`backfill attempt failed — ${err?.stack || err?.message || err}`);
      }
      await sleep(intervalMs);
    }
  })();

  return () => { stopped = true; };
}
